-- MySQL Script generated by MySQL Workbench
-- Sat Mar 22 18:07:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adam` DEFAULT CHARACTER SET utf8mb4 ;
USE `adam` ;

-- -----------------------------------------------------
-- Table `adam`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adam`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`topic` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `iduser_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `adam`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adam`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `file` BLOB NOT NULL,
  `topic_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_topic_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `adam`.`topic` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adam`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT(65535) NOT NULL,
  `isBot` TINYINT NOT NULL,
  `topic_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_topic_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `adam`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adam`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`question` (
  `id` INT NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `isQCM` TINYINT NOT NULL,
  `topic_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_topic_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `adam`.`topic` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adam`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adam`.`answer` (
  `id` INT NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `correct` TINYINT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_question_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `adam`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
