version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: adam-frontend
    ports:
      - '4200:4200'
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - adam-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: adam-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=adam
      - FRONTEND_URL=http://localhost:4200
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_URL=http://chromadb:8000
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
      - ./Backend/uploads:/app/uploads
    env_file:
      - ./Backend/.env
    depends_on:
      - chromadb
      - mysql
    command: >
      sh -c "sleep 20 && npm run start:dev"
    networks:
      - adam-network

  mysql:
    image: mysql:8.0
    container_name: adam-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=adam
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_general_ci
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - adam-network
      
  chromadb:
    image: chromadb/chroma
    container_name: adam-chromadb
    restart: unless-stopped
    volumes:
      - ./ChromaDB/chroma_db:/chroma/chroma
    ports:
      - '8000:8000'
    environment:
      - ALLOW_RESET=True
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - adam-network

networks:
  adam-network:
    driver: bridge

volumes:
  mysql_data:
  frontend_node_modules:
  backend_node_modules: