# Generated by Django 5.1.7 on 2025-03-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="name",
            new_name="title",
        ),
    ]
