version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: always
    ports:
      - '4200:80'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development